version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:alpine-slim
    ports:
      - 80:80
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx/public:/usr/share/nginx/html/static"
    depends_on:
      - ted-search

  ted-search:
    container_name: cowsay
    image: some-cowsay:1.0
